spring:
  data:
      datasource:
        connection: default
        projectId:  virgin-red-prod
        jsonFile: virgin-red-prod-915810871cdd.json
server:
  port: 8090

cache.type: Hazelcast
cache.url: 127.0.0.1:5701

#logging:
#  pattern:
#    console: '%d{HH:mm:ss.SSS} | %msg%n'